config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Snippets API",
      default_version='v1',
      description="Test description",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include('interface.urls', namespace='interface')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),

    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc')

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

interface/urls.py
from django.urls import path


from interface.views import UserCreateView, SmsCodeView, UserDetailView, UserUpdateView
from interface.apps import InterfaceConfig

app_name = InterfaceConfig.name

urlpatterns = [
    path('', UserCreateView.as_view(), name='login'),
    path('sms_code', SmsCodeView.as_view(), name='sms_code'),
    path('user_detail', UserDetailView.as_view(), name='user_detail'),
    path('user_update', UserUpdateView.as_view(), name='user_update'),
]

users/urls.py
from django.urls import path
from rest_framework_simplejwt.views import (TokenObtainPairView, TokenRefreshView)
from rest_framework.permissions import AllowAny

from users.apps import UsersConfig

from users.views import UserCreateAPIView, UserProfileRetrieveAPIView, UserUpdateAPIView, UserListAPIView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', UserCreateAPIView.as_view(), name='login'),
    path('users/<int:pk>/', UserProfileRetrieveAPIView.as_view(), name='users_retrieve'),
    path('users/<int:pk>/update/', UserUpdateAPIView.as_view(), name='users_update'),
    path("", UserListAPIView.as_view(), name="user_list"),

    path('token/', TokenObtainPairView.as_view(permission_classes=(AllowAny,)), name='token'),
    path('token/refresh/', TokenRefreshView.as_view(permission_classes=(AllowAny,)), name='token_refresh'),
]

interface/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

from users.validators import phone_validator

NULLABLE = {'null': True, 'blank': True}


class User(AbstractUser):
    username = None

    phone = models.CharField(max_length=16, unique=True, verbose_name='Телефон',
                             help_text='Введите номер телефона в формате 79997776655', validators=[phone_validator])
    name = models.CharField(max_length=50, verbose_name='Имя', help_text='Введите имя', **NULLABLE)
    last_name = models.CharField(max_length=50, verbose_name='Фамилия', help_text='Введите фамилию', **NULLABLE)
    invite_code = models.CharField(max_length=6, unique=True, verbose_name='Инвайт-код')
    activated_invite_code = models.CharField(max_length=6, verbose_name='Активированный инвайт-код', **NULLABLE)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.phone

interface/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.forms import ModelForm, forms, CharField, Form

from users.models import User


class UserRegisterForm(ModelForm):
    """Форма для регистрации пользователя."""
    class Meta:
        model = User
        fields = ('phone', )


class UserUpdateForm(UserChangeForm):
    """Форма для обновления данных пользователя."""
    def clean_ref_code(self):
        # Проверяем activated_invite_code
        activated_invite_code = self.cleaned_data.get('activated_invite_code')  # Получаем значение поля activated_invite_code

        # Проверяем, использовался ли уже код
        if self.instance.activated_invite_code:
            raise forms.ValidationError('Вы уже использовали код')

        # Обрабатываем случаи, когда код не был введен
        if not activated_invite_code:
            return activated_invite_code

        # Проверка на использование собственного инвайт-кода
        if activated_invite_code == self.instance.invite_code:
            raise forms.ValidationError('Вы не можете использовать свой же код!')

        # Проверяем, существует ли указанный инвайт-код
        if not User.objects.filter(invite_code=activated_invite_code).exists():
            raise forms.ValidationError('Пригласительный код не найден!')

        return activated_invite_code  # Возвращаем корректное значение

    class Meta:
        model = User  # Указываем, что эта форма работает с моделью User
        fields = ('name', 'last_name', 'activated_invite_code',)  # Поля для обновления


class SmsCodeForm(Form):
    """Форма для ввода кода из смс."""
    code = CharField(label='Код из СМС')  # Поле для ввода 4-значного кода, отправленного по SMS

interface/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, DetailView, UpdateView
from django.views import View
from django.contrib import messages
from django.contrib.auth import authenticate, login

from interface.forms import UserRegisterForm, UserUpdateForm, SmsCodeForm
from users.models import User
from users.services import generate_invite_code, create_unique_invite_code, send, generate_sms_code


class UserCreateView(CreateView):
    """Сохранение пользователя при первом входе, отправка кода для входа, присваивание invite_code при первом входе"""
    template_name = 'interface/register.html'
    model = User
    form_class = UserRegisterForm  # Форма для регистрации пользователя
    success_url = reverse_lazy('interface:login')  # URL для перенаправления при успешной регистрации

    def get_success_url(self):
        # Формируем URL для работы с кодом, добавляя номер телефона в параметры запроса
        return reverse_lazy('interface:sms_code') + '?phone=' + self.object.phone

    def form_valid(self, form, *args, **kwargs):
        return_data = {}

        form.is_valid()
        user = form.save()  # Сохраняем пользователя из валидной формы
        user.invite_code = create_unique_invite_code()  # Генерируем и присваиваем инвайт-код
        return_data['invite_code'] = user.invite_code

        password = generate_sms_code()  # Генерируем временный пароль
        user.set_password(password)  # Устанавливаем сгенерированный пароль

        # Отправляем SMS с временным кодом
        # sms_response = send(int(user.phone), f'Ваш код: {password}')  # Убедитесь, что номер телефона хранится в user.phone
        user.save()  # Сохраняем изменения в пользователе

        return super().form_valid(form)  # Переход к следующему шагу

    def form_invalid(self, form, *args, **kwargs):
        # Если форма невалидна, пытаемся получить уже существующего пользователя
        user = User.objects.get(phone=form.data.get('phone'))

        password = generate_sms_code()  # Генерируем новый пароль
        user.set_password(password)  # Устанавливаем новый пароль

        # sms_response = send(int(user.phone), f'Ваш код: {password}')  # Убедитесь, что используется правильный номер
        user.save()  # Сохраняем пользователя

        self.object = user  # Обновляем объект пользователя
        return redirect(self.get_success_url())  # Переход к следующему шагу


class SmsCodeView(View):
    """Проверка кода из SMS и авторизация пользователя"""

    def post(self, *args, **kwargs):
        phone = self.request.POST.get('phone')  # Получаем номер телефона из POST-запроса
        code = self.request.POST.get('code')  # Получаем код из POST-запроса
        user = authenticate(self.request, username=phone, password=code)  # Проверяем пользователя
        if user is not None:
            login(self.request, user)  # Если пользователь аутентифицирован, выполняем вход
            # Перенаправляем на страницу с успехом после логина
            return redirect(reverse('interface:user_detail'))
        else:
            # Если аутентификация не прошла, перенаправляем на страницу логина
            return redirect(reverse('interface:login'))

    def get(self, *args, **kwargs):
        form = SmsCodeForm()  # Создаем экземпляр формы для ввода кода
        return render(self.request, 'interface/sms_code.html', {'form': form})  # Отображаем форму


class UserDetailView(DetailView):
    """Отображение данных пользователя"""

    model = User  # Модель для отображения данных
    template_name = 'interface/user_detail.html'  # Шаблон для показа деталей пользователя

    def get_object(self, queryset=None):
        # Получаем текущего пользователя из запроса
        return self.request.user


class UserUpdateView(UpdateView):
    """Обновление данных пользователя"""

    model = User  # Модель для обновления данных
    template_name = 'interface/user_form.html'  # Шаблон для формы обновления
    form_class = UserUpdateForm  # Форма для обновления данных пользователя
    success_url = reverse_lazy('interface:user_detail')  # URL для перенаправления после успешного обновления

    def get_object(self, queryset=None):
        # Получаем текущего пользователя для обновления его данных
        return self.request.user

    def get_success_url(self):
        # Формируем URL для перенаправления, добавляя номер телефона в параметры запроса
        return reverse_lazy('interface:user_detail') + '?phone=' + self.object.phone

users/views.py
from rest_framework.generics import CreateAPIView, RetrieveAPIView, UpdateAPIView, ListAPIView
from rest_framework.permissions import AllowAny, IsAuthenticated, IsAdminUser
from rest_framework import status, generics
from rest_framework.response import Response
from django.shortcuts import get_object_or_404

from users.models import User
from users.permissions import IsUser
from users.serializers import UserSerializer, ProfileSerializer

from users.services import create_unique_invite_code, send, generate_sms_code


class UserCreateAPIView(CreateAPIView):
    """Обработка создания пользователей.
    При первом входе сохраняет пользователя,
    присваивает invite_code и высылает код CVC для входа.
    """
    serializer_class = UserSerializer  # Указываем сериализатор для обработки данных
    queryset = User.objects.all()  # Определяем, что будем работать со всеми пользователями
    permission_classes = (AllowAny,)  # Разрешаем доступ всем пользователям

    def post(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)  # Получаем сериализатор с данными запроса
        data_dict = {}  # Словарь для хранения данных ответа
        try:
            # Проверяем данные, если невалидные - выбрасываем исключение
            serializer.is_valid(raise_exception=True)
            user = serializer.save()  # Сохраняем пользователя

            # Генерируем и присваиваем уникальный пригласительный код
            user.invite_code = create_unique_invite_code()
            data_dict['invite_code'] = user.invite_code  # Добавляем код в ответ

            # Генерируем код для авторизации и устанавливаем его как пароль пользователя
            code = generate_sms_code()  # Генерируем код для авторизации
            user.set_password(code)  # Устанавливаем сгенерированный пароль
            user.save()  # Сохраняем изменения в пользователе

            # Отправляем сообщение с кодом авторизации (сначала проверяем, был ли успешно создан пользователь)
            # if user.phone:  # Если номер телефона пользователя существует
            #     send(int(user.phone), f'Ваш код авторизации: {code}')  # Отправляем SMS с кодом
            # else:
            #     data_dict['error'] = 'У пользователя отсутствует номер телефона.'  # Обработка случая отсутствия телефона

        except Exception as e:
            # Обработка других ошибок (например, если номер телефона не уникален в случае создания)
            user = User.objects.filter(phone=request.data.get('phone')).first()
            if user:
                data_dict['invite_code'] = user.invite_code  # Возвращаем код существующего пользователя
            else:
                data_dict['error'] = str(e)  # Возвращаем сообщение об ошибке

        # Возвращаем ответ с кодом 201 и данными
        return Response(data_dict, status=status.HTTP_201_CREATED)


class UserProfileRetrieveAPIView(RetrieveAPIView):
    """Обработка отображения данных пользователя"""
    serializer_class = ProfileSerializer  # Указываем сериализатор для отображения профиля
    queryset = User.objects.all()  # Определяем, что будем работать со всеми пользователями
    permission_classes = (IsAuthenticated, IsUser)  # Только аутентифицированные пользователи с правами

    def get_object(self, *args, **kwargs):
        return get_object_or_404(User, pk=self.kwargs['pk'])


class UserUpdateAPIView(UpdateAPIView):
    """Обработка обновления данных пользователя"""
    serializer_class = UserSerializer  # Указываем сериализатор для обработки данных
    queryset = User.objects.all()  # Определяем, что будем работать со всеми пользователями
    permission_classes = (IsAuthenticated, IsUser)  # Только аутентифицированные пользователи с правами

    def get_object(self, *args, **kwargs):
        return get_object_or_404(User, pk=self.kwargs['pk'])


class UserListAPIView(ListAPIView):
    """Обработка списка данных пользоватеей"""
    serializer_class = ProfileSerializer  # Указываем сериализатор для обработки данных
    queryset = User.objects.all()  # Определяем, что будем работать со всеми пользователями
    permission_classes = (IsAuthenticated,)  # Только аутентифицированные пользователи

interface/templates/interface/base.html
{% load static %}

<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
<!--    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">-->
<!--    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">-->
<!--    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">-->
<!--    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">-->
<!--    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">-->
<!--    <meta name="theme-color" content="#712cf9">-->


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<main>

    {% block content %}
    {% endblock %}

</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

interface/templates/interface/register.html
{% extends 'interface/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-20">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

interface/templates/interface/sms_code.html
{% extends 'interface/base.html' %}
{% block content %}

<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-20">
            <div class="card">
                <div class="card-body">
                    {% csrf_token %}
                    <input type="hidden" name="phone" value="{{request.GET.phone}}">
                    {{ form.as_p }}
                </div>
                <button type="submit" class="btn btn-primary">
                    Войти
                </button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

interface/templates/interface/user_detail.html
{% extends 'interface/base.html' %}
{% block content %}

<section class="py-5 text-center container">
    <div class="col-lg-6 col-md-8 mx-auto">
        <h3 class="font-weight-bold">Профиль пользователя</h3>
    </div>
</section>

<div class="container">
    <div class="col-20">
        <div class="card">
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <p class="card-text">Телефон: {{user.phone}}</p>
                <p class="card-text">Имя: {{user.name}}</p>
                <p class="card-text">Фамилия: {{user.last_name}}</p>
                <p class="card-text">Пригласительный код: {{user.invite_code}}</p>
                <p class="card-text">Использованный пригласительный код: {{user.activated_invite_code}}</p>
                <p class="card-text">Пользователи с вашим пригласительным кодом: {% for i in user.get_invited_users %}</p>
                <p class="mb-2">{{i}}<br/></p>
                {% endfor %}
            </div>

            <a class="btn btn-primary rounded" href="{% url 'interface:user_update' %}" role="button">Редактировать</a>
            <a class="btn btn-danger" href="{% url 'interface:login' %}" role="button">Выйти</a>

        </div>

    </div>
</div>
{% endblock %}

interface/templates/interface/user_form.html
{% extends 'interface/base.html' %}
{% block content %}
<section class="py-5 text-center container">
    <div class="col-lg-6 col-md-8 mx-auto">
        <h3 class="font-weight-bold">Редактирование профиля</h3>
    </div>
</section>
<div class="container">
    <form class="row" method="post">
        <div class="col-6">
                <div class="card-body">
                    <div class="col-lg-6 col-md-8 mx-auto">
                        <h7 class="font-weight-bold"> Телефон: {{user.phone}}</h7>
                    </div>
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">
                        Сохранить
                    </button>
                    <a class="btn btn-danger" href="{% url 'interface:user_detail' %}"
                       role="button">Назад</a>
                </div>
            </div>
    </form>
</div>
{% endblock %}